/**
*
*  Purpose          :   Controller extension class for "GenericDetailPageUsingFS"
                        Basicall it is going to have server side needed code to build dynamic datail page in generic way.
*
*  Created Date     :   04/22/2023
*
*  Created By       :   Amit Kumar
*
*  Revision Logs    :   V_1.0 - Created
*
**/
public with sharing class GenericDetailPageUsingFSController_Ext 
{
    public GenericDetailPageUsingFSController_Ext(Apexpages.StandardController stdController)
    {
        
    }
}